### ISSUE TITLE
Error when creating patch

### ISSUE THREAD

**Issue by horrop** [fayaz12g/totk-aar#3] opened 2023-06-02 11:08 UTC
Traceback (most recent call last):
  File "C:\Users\user\Desktop\AAR 2.1.0\download.py", line 4, in <module>
    import requests
  File "C:\Users\user\Desktop\AAR 2.1.0\requests\__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
0070201E
0070201E
Patch file created: C:/Users/user/Desktop/EA 3599/user/load/0100F2C0115B6000/AAR MOD\AAR MOD\exefs\main-1.0.0.pchtxt
0070201E
0070201E
Patch file created: C:/Users/user/Desktop/EA 3599/user/load/0100F2C0115B6000/AAR MOD\AAR MOD\exefs\main-1.1.0.pchtxt
0070201E
0070201E
Patch file created: C:/Users/user/Desktop/EA 3599/user/load/0100F2C0115B6000/AAR MOD\AAR MOD\exefs\main-1.1.1.pchtxt
0070201E
0070201E
Patch file created: C:/Users/user/Desktop/EA 3599/user/load/0100F2C0115B6000/AAR MOD\AAR MOD\exefs\main-1.1.2.pchtxt
Input file not found.
Invalid BLARC file path.
Centered HUD value is set to  True
The scaling factor is  0.7619047619047619
Traceback (most recent call last):
  File "C:\Users\user\Desktop\AAR 2.1.0\script.py", line 21, in <module>
    file_names = os.listdir(blyt_folder)
                 ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/user/Desktop/EA 3599/user/load/0100F2C0115B6000/AAR MOD\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN\\blyt'
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "GUI.py", line 139, in create_patch
    os.remove(blarc_file_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/user/Desktop/EA 3599/user/load/0100F2C0115B6000/AAR MOD\\AAR MOD\\temp\\Common.Product.110.Nin_NX_NVN.blarc'

**Comment by fayaz12g** [comment] 2023-06-02 13:34
The issue is fixed in 2.1.1

**Closed by fayaz12g** 2023-06-02 13:34 UTC
