### ISSUE TITLE
Header and footer bars circles decor are stretched

### ISSUE THREAD

**Issue by InterClaw** [fayaz12g/totk-aar#44] opened 2023-07-20 18:32 UTC
Nice that you have extended the header bar when saving as of 7.0.0!

Now I noticed though that the circle pattern decor is stretched in both the header and footer bars in the UI. It was probably always like this and I just didn't think about it.

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/a6946b7d-71c1-4a5e-98e9-ad7046f30ed6)

**Comment by Fruithapje21** [comment] 2023-07-20 20:30
Fixed in v2.4.0 of TOTK-Ultrawide

**Comment by InterClaw** [comment] 2023-07-20 21:21
Downloaded it and tried it out. This is what it looks like for me.

Everything in the UI is stretched when I use this. Only the 3D space and Link in the menu look correct. 😞 

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/23398083-a507-4605-bb25-1e70b3294d7a)

**Comment by Fruithapje21** [comment] 2023-07-20 22:11
I'm not sure what you downloaded and which mods you have enabled, but if you download from [here](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FFruithapje21%2FTOTK-Ultrawide%2Ftree%2Fmain%2Fmods%2FTOTK-Ultrawide%252021.5-9rl) and disable the AAR mod it should work. Fayaz will probably update the files in this repo somewhere tomorrow.

**Comment by InterClaw** [comment] 2023-07-20 22:37
Got it from here and generated it on my own. 👍 
https://github.com/Fruithapje21/TOTK-Ultrawide/releases/tag/v2.4.0

It's the controller mod that breaks it, since they're using the same files, huh. 🤦‍♂️  Looking forward to the AAR MOD version then. 👍

**Comment by fayaz12g** [comment] 2023-07-21 01:46
Thanks @Fruithapje21 for fixing this, @InterClaw I’ll include those changes tonight!

**Comment by fayaz12g** [comment] 2023-07-21 03:56
@InterClaw https://github.com/fayaz12g/totk-aar/releases/tag/dev720f fixes the issue (it is not in the release version yet as I'm waiting finish my GUI updates before making it a release, but it still fully works as intended)

**Closed by fayaz12g** 2023-07-21 03:56 UTC
